void System_Init(void);
void System_Quit(void);
int System_PollKeys(int *);
void System_VideoUpdate(void);
void System_Border(int);
int System_Rnd(void);
void System_UpdateKeys(void);
int System_IsKeyLeft(void);
int System_IsKeyRight(void);
int System_IsKeyJump(void);
void System_SetPixel(int, int);
void System_AudioLock(void);
void System_AudioUnlock(void);
void System_LockTexture(void);
void System_UnlockTexture(void);
void System_Delay(void);
